# Form implementation generated from reading ui file 'Chuong1_Ham/baitap21/ui/MainWindow21.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 378)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonThucHien = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonThucHien.setGeometry(QtCore.QRect(210, 190, 56, 17))
        self.pushButtonThucHien.setStyleSheet("background-color: rgb(255, 187, 170);")
        self.pushButtonThucHien.setObjectName("pushButtonThucHien")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 481, 61))
        self.label.setStyleSheet("color: rgb(255, 0, 127);\n"
"background-color: rgb(255, 192, 196);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(70, 70, 341, 111))
        self.groupBox.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 251, 196);\n"
"color: rgb(226, 212, 8);")
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(40, 20, 61, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(40, 60, 71, 21))
        self.label_3.setObjectName("label_3")
        self.lineEditN = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditN.setGeometry(QtCore.QRect(180, 30, 113, 20))
        self.lineEditN.setObjectName("lineEditN")
        self.lineEditK = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditK.setGeometry(QtCore.QRect(180, 60, 113, 20))
        self.lineEditK.setObjectName("lineEditK")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(70, 220, 341, 111))
        self.groupBox_2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 170, 127);\n"
"background-color: rgb(123, 192, 172);")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(40, 20, 61, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(40, 60, 71, 21))
        self.label_5.setObjectName("label_5")
        self.lineEditA = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditA.setGeometry(QtCore.QRect(180, 30, 113, 20))
        self.lineEditA.setObjectName("lineEditA")
        self.lineEditC = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditC.setGeometry(QtCore.QRect(180, 60, 113, 20))
        self.lineEditC.setObjectName("lineEditC")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonThucHien.setText(_translate("MainWindow", "Thực hiện"))
        self.label.setText(_translate("MainWindow", "CHỈNH HỢP - TỔ HỢP"))
        self.groupBox.setTitle(_translate("MainWindow", "Nhập N và K"))
        self.label_2.setText(_translate("MainWindow", "Nhập N"))
        self.label_3.setText(_translate("MainWindow", "Nhập K"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Kết quả"))
        self.label_4.setText(_translate("MainWindow", "A ="))
        self.label_5.setText(_translate("MainWindow", "C ="))
